# Generated by Django 5.0.3 on 2024-03-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_info_profile_aboutme_profile_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
