# Generated by Django 5.0.3 on 2024-04-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('INVESTOR', 'INVESTOR'), ('PARTNER', 'PARTNER'), ('SADMIN', 'SADMIN')], default='INVESTOR', max_length=20),
        ),
    ]
