# Generated by Django 5.0.3 on 2024-04-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_personaldetail_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='fullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
