# Generated by Django 5.0.3 on 2024-04-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_personaldetail_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='marital_status',
        ),
    ]
