# Generated by Django 5.0.3 on 2024-04-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_partner_slug_partner_partner_referral_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='partner_referral',
            new_name='partner_code',
        ),
    ]
