# Generated by Django 5.0.3 on 2024-04-02 14:00

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_partner_partner_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='state',
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FAMALE', 'FAMALE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='id_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='id_type',
            field=models.CharField(blank=True, choices=[('IDCARD', 'KTP'), ('PASSPORT', 'PASSPORT'), ('DRIVING_LICENSE', 'DRIVING LICENSE')], default='IDCARD', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='postal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
